repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        types: [file, python]
        additional_dependencies: [black]

      - id: ruff
        name: ruff
        entry: ruff check --fix
        language: python
        types: [file, python]
        additional_dependencies: [ruff]
